---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: r4k-config
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-ceph-block
