---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.2.26
    env:
      TZ: "America/New York" 
    service:
      main:
        ports:
          https:
            port: 8443
            type: LoadBalancer
            annotations:
              traefik.ingress.kubernetes.io/service.serversscheme: https
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
          controller:
            enabled: true
            port: 8080
            protocol: TCP
            type: LoadBalancer
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
          portal-http:
            enabled: true
            port: 8080
            protocol: HTTP
            type: LoadBalancer
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
          portal-https:
            enabled: true
            port: 8443
            protocol: HTTPS
            type: LoadBalancer
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
            type: LoadBalancer
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
          stun:
            enabled: true
            port: 3478
            protocol: UDP
            type: LoadBalancer
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
            type: LoadBalancer
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
            type: LoadBalancer
            externalIPs: 
            - "${SVC_UNIFI_ADDR}"
            externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: unifi.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - hosts:
              - unifi.${SECRET_DOMAIN}
            secretName: unifi-cert
    persistence:
      data:
        enabled: true
        existingClaim: unifi-data
    resources:
      requests:
        cpu: "0.02"
        memory: "1024M"
      limits:
        memory: "1536M"
