---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.2.26

    env:
      TZ: "America/New_York"

    service:
      main:
        type: LoadBalancer
        annotations:
          #coredns.io/hostname: unifi
          traefik.ingress.kubernetes.io/service.serversscheme: https
        loadBalancerIP: ${SVC_UNIFI_ADDR}
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          #cert-manager.io/cluster-issuer: letsencrypt-production
          #external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          #traefik.ingress.kubernetes.io/router.middlewares: system-ingress-rfc1918-ips@kubernetescrd

        hosts:
          - host: unifi.${SECRET_DOMAIN}
            paths:
              - path: /

        tls:
          - hosts:
              - unifi.${SECRET_DOMAIN}

    resources:
      requests:
        cpu: "0.02"
        memory: "1024M"
      limits:
        memory: "1536M"

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config

    mongodb:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      persistence:
        enabled: true
        existingClaim: unifi-mongodb
