---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unifi
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unifi
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: jacobalberty/unifi
      tag: v6.2.26
    timezone: "America/New_York"
    runAsRoot: false
    guiService:
      type: LoadBalancer
      externalIPs: 
      - "${SVC_UNIFI_ADDR}"
      externalTrafficPolicy: Local
    captivePortalService:
      type: LoadBalancer
      externalIPs: 
      - "${SVC_UNIFI_ADDR}"
      externalTrafficPolicy: Local
    controllerService:
      type: LoadBalancer
      externalIPs: 
      - "${SVC_UNIFI_ADDR}"
      externalTrafficPolicy: Local
    stunService:
      type: LoadBalancer
      externalIPs: 
      - "${SVC_UNIFI_ADDR}"
      externalTrafficPolicy: Local
    discoveryService:
      type: LoadBalancer
      externalIPs: 
      - "${SVC_UNIFI_ADDR}"
      externalTrafficPolicy: Local
    syslogService:
      type: LoadBalancer
      externalIPs: 
      - "${SVC_UNIFI_ADDR}"
      externalTrafficPolicy: Local
    speedtestService:
      type: LoadBalancer
      externalIPs: 
      - "${SVC_UNIFI_ADDR}"
      externalTrafficPolicy: Local
    ingress:
      ingressClassName: "traefik"
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - "unifi.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "unifi.${SECRET_DOMAIN}"
        secretName: unifi-cert
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      existingClaim: unifi-config-v1
    mongodb:
      enabled: false
    logging:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.2.1
          pullPolicy: IfNotPresent
        loki:
          url: http://loki:3100/loki/api/v1/push
