---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-v1
  namespace: networkin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
