---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-mongodb
  namespace: networking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-ceph-block
