apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-ro
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
#  namespace: string
spec:
  accessModes:
    - ReadOnlyMany
#    - string
  capacity:
    storage: 8000Gi
#    key: string
  nfs:
    path: /mnt/shares
    readOnly: true
    server: 172.19.0.1
