#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: ghcr.io/k8s-at-home/sonarr
  pullPolicy: IfNotPresent
  tag: v3.0.6.1265

strategy:
  type: Recreate

env:
  TZ: "America/New_York"

service:
  port:
    port: 8989

ingress:
  enabled: true
  hosts:
    - host: sonarr.mrry.io
      paths:
        - path: /
          pathType: Prefix

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
        - /usr/bin/env
        - bash
        - -c
        - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
          read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 512Mi
    skipuninstall: true

  media:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    size: 8000Gi
    skipuninstall: true
    existingClaim: "nfs-media-rw"

podSecurityContext:
  runAsUser: 568 
  runAsGroup: 568         
  fsGroup: 568

# Enable gathering Prometheus metrics
prometheus:
  podMonitor:
    enabled: false
    interval: 3m
    scrapeTimeout: 1m
    additionalLabels: {}

# # When using the prometheus.podMonitor the following
# # container is required
# additionalContainers:
# - name: exportarr
#   image: ghcr.io/onedr0p/exportarr:v0.6.0
#   imagePullPolicy: IfNotPresent
#   args: ["exportarr", "sonarr"]
#   env:
#   - name: PORT
#     value: "32123"
#   - name: URL
#     value: "http://localhost"
#   - name: CONFIG
#     value: "/config/config.xml"
#   ports:
#   - name: exportarr
#     containerPort: 32123
#   volumeMounts:
#   - name: config
#     mountPath: /config
#     readOnly: true

