---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: utils
spec:
  interval: 5m
  chart:
    spec: 
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.2.0
    env:
      TZ: "America/New_York"
    hajimari:
      defaultEnable: "false"
      title: "startpage"
      name: "Dave"
      namespaceSelector:
        matchNames:
        - media
        - utils
        - monitoring
        - networking
        - security
      groups:
      - name: Communicate
        links:
        - name: Discord
          url: 'https://discord.com'
        - name: Outlook
          url: 'https://outlook.office.com'
      - name: Cloud
        links:
        - name: OneDrive
          url: 'https://onedrive.office.com'
        - name: Backblaze
          url: 'https://backblaze.com'
      - name: Dev
        links:
        - name: Codepen
          url: 'https://codepen.io/'
        - name: Devdocs
          url: 'https://devdocs.io'
        - name: Devhints
          url: 'https://devhints.io'
      - name: Media
        links:
        - name: Netflix
          url: 'http://netflix.com'
        - name: Spotify
          url: 'http://browse.spotify.com'
        - name: Trakt
          url: 'http://trakt.tv'
        - name: YouTube
          url: 'https://youtube.com/feed/subscriptions'
      - name: Reading
        links:
        - name: Medium
          url: 'http://medium.com'
        - name: Reddit
          url: 'http://reddit.com'
      - name: Tech
        links:
        - name: Hacker News
          url: 'https://news.ycombinator.com/'
        - name: The Verge
          url: 'https://theverge.com/'
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-authentik@kubernetescrd"
        hosts:
        - host: "startpage.${SECRET_DOMAIN}"
          paths: 
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "startpage.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    resources:
      requests:
        cpu: 100m
        memory: 128M
