---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-nas-pv
spec:
  storageClassName: media-nas
  capacity:
    storage: 10000Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.18.0.15
    path: /media
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-nas-pvc
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10000Mi
