---

# Control Plane registration address [kube-vip]
k3s_registration_fqdn: cl.k3s.mrry.io
k3s_registration_ip: 172.25.0.1

# k3s network options
k3s_cluster_cidr: 172.26.0.0/16
k3s_service_cidr: 172.27.0.0/16
