---

- hosts:
  - master-nodes
  - worker-nodes
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
  - name: Pausing for 3 seconds...
    pause:
      seconds: 3
  roles:
  - debian
  - xanmanning.k3s
  - k3s
  - kube-vip
