---
# All nodes
- name: Update all nodes
  hosts: kube
  remote_user: root
  tasks:

  - name: update system
    apt: 
      update_cache: yes
      upgrade: dist

  - name: install curl
    apt:
      name: curl 
      state: present

  - name: install git
    apt:
      name: git
      state: present

  - name: install sudo
    apt:
      name: sudo
      state: present

  - name: Add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_ipv4 }} {{item}}"
      state: present
    when: hostvars[item].ansible_ipv4 is defined
    with_items: "{{ groups.all }}"

# Workers
- name: Update all nodes
  hosts: workers
  remote_user: root
  tasks:
  - name: install nfs
    apt:
      name: nfs-common


