authentik:
    token: ENC[AES256_GCM,data:mbeCBX9WyiY4KkDYwIVNWSkydc+kUa/W8MJF3uid/XfKOSWGaEcwtMhblovtjmx/zBKot8J0WvIi7csyaNVpiBPekePAuRWCh1wS1+yZkjj1OtFjbtGqfPOcIebaJ8QTYh/S6tngdENcGmA+roK8wanZ2fuESbE0NLMGdZXfRRk=,iv:xJmwWlvENvHOuNaDF7aExJp7ZacdWPDk/I0lmyJsDyw=,tag:HoAxxyqKeJoLTophnwRd9g==,type:str]
secret:
    domain: ENC[AES256_GCM,data:WE2htPPC1A==,iv:SlRXHgSBklc8jax7663Zkk0jcGbfMSWWgzpFDRuVVvo=,tag:4B2yr1zlOESBGGA2VnVcXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-01T00:20:15Z"
    mac: ENC[AES256_GCM,data:qmCRz4Q4Fi7DTIaRI5GiuVN6yY2rUV4tjzu52/gTydv4Y2WLGFZrCiEW1i+gTXy3PZq/tmhAMhoirEd8fxjBFT231jIwSDPcIagToWpO5fHOYnRqkbfT51EgIY1PQBFMcOeIz3PNsuR6cwbr+vmcOO145or6nYHo5MLp8qfSHUA=,iv:f9fWuCzliZ4bl4jH9TbaXMqcnEEqsE1HsE3bn2Pg90w=,tag:s2rEQOW6cO439L0B96oUNQ==,type:str]
    pgp:
        - created_at: "2021-05-24T20:09:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8mUYP7vXQBBAQwA4Dp0qTeJxDOUOVMjgCCKHvmXeftKoNkHROtUhs24u+hC
            yk9GY3TIqtvmY2QTgtOOfdusEiZdYE0U3//hQnXBWMfNTZNJGfFVBC4+FUWw6MYW
            ExG09K4HH76MKRqh1wNTTczlnse2wUc05iuqU3f5DV63wNDrBICJVqe8Fqrr/DNX
            Aqaxq0WpL6yAgbsbqqtCNZuyBFj/dvWH0rgP+PgHoQpK6aIeqeaM8MSl10QiRASN
            hMldC/BZtHnNEX9uYBKxFZDvQneCvF2qzpzjJr7iyl8txlP6mxAjw4UpCSlmszFL
            U2LlCa3/DyPRubrzN62mu9Eh/iDKCEBMaesdpMdpFx4i7tyN1/wMzBSyiz2jTcZQ
            enuA5AbZ6P5SuP80addeZ5A5BI+vRkLtgeqf7CM07k4WPoYU08waXS2CN8KASre2
            KmuZq/4f/DzjGpBLe00P76DV591cLpz2Xwlgv51/igGJMcXRMqxSxKBjrIyrjdCg
            glSMxATlSF3F9WA1L9iY0l4BiTG8k4dcHVrTmDk2YFZA6AlnXugz9kXitPmQoDBp
            MGTbePql0OQucFKyz5HKDHR5fYdcSORvfiuW1wDB8bk1IpBXtKBDKNceefaVwriX
            aL1E/nlykIarqDYtULuz
            =2Wxm
            -----END PGP MESSAGE-----
          fp: 1797E88B0B0CE9D2514A1C841F4200D33179FA67
    unencrypted_suffix: _unencrypted
    version: 3.7.1
