---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cryptofolio
  namespace: utils
spec:
  interval: 5m
  chart:
    spec: 
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: cryptofolio
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: xtrendence/cryptofolio
      tag: V.2.2.0
      pullPolicy: IfNotPresent
    env:
      TZ: "America/New_York"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "chart-box"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-authentik@kubernetescrd"
        hosts:
        - host: "cryptofolio.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "cryptofolio.${SECRET_DOMAIN}"
    persistence: 
      config:
        enabled: true
        existingClaim: cryptofolio-config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 500Mi
