---

- name: remove pve-enterprise 
  ansible.builtin.lineinfile: 
    dest: /etc/apt/sources.list.d/pve-enterprise.list    
    regex: '^deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise'
    state: absent
  
- name: add pve-no-subscription
  ansible.builtin.lineinfile: 
    dest: /etc/apt/sources.list.d/pve-enterprise.list      
    line: deb http://download.proxmox.com/debian buster pve-no-subscription
    state: present
