---

- name: Check for existence of grub
  stat:
    path: /etc/default/grub
  register: grub_result

- name: Check if Grub Arg is missing
  become: true
  shell: "grep '{{ item }}' /etc/default/grub"
  register: lineinfile_check
  failed_when: "lineinfile_check.rc == 2"
  changed_when: "lineinfile_check.rc == 1"
  ignore_errors: yes

- name: Add Grub Arg
  become: true
  lineinfile:
    backrefs: yes
    path: /etc/default/grub
    regexp: "^(GRUB_CMDLINE_LINUX_DEFAULT=\".*)\"$"
    line: "\\1 {{ item }} \""
  when: lineinfile_check.changed

- name: Update grub
  become: true
  shell: update-grub

