--- 

- include: apt-sources.yml 
  tags:
  - apt-sources

- include: grub.yml
  loop:
    - "intel_iommu=on"
    - "iommu=pt"
  tags:
  - grub

- include: modules.yml
  loop:
    - "vfio"
    - "vfio_iommu_type1"
    - "vfio_pci"
    - "vfio_virqfd"
  tags:
  - modules

- include: packages.yml
  tags:
  - packages

