---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zabbix
  namespace: monitoring
spec:
  interval: 5m

zabbixServer:
  replicaCount: 1
  hostPort: false
  hostIP: 0.0.0.0
  resources: {}
  image:
    repository: zabbix/zabbix-server-pgsql
    tag: ubuntu-5.4.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  DB_SERVER_HOST: "zabbix-postgresql"
  POSTGRES_USER: "zabbix"
  POSTGRES_PASSWORD: ""${SECRET_ZABBIX_DB_PW}""
  POSTGRES_DB: "zabbix"
  service:
    type: ClusterIP
    port: 10051

postgresql:
  enabled: true
  postgresqlUsername: zabbix
  postgresqlPassword: "${SECRET_ZABBIX_DB_PW}"
  postgresqlDatabase: zabbix
  postgresqlPostgresPassword: "${SECRET_ZABBIX_DB_PW}"

zabbixagent:
  enabled: true
  resources: {}
  image:
    repository: zabbix/zabbix-agent
    tag: ubuntu-5.4.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  ZBX_HOSTNAME: zabbix-agent
  ZBX_SERVER_HOST: 127.0.0.1
  ZBX_SERVER_PORT: 10051
  ZBX_PASSIVE_ALLOW: true
  ZBX_PASSIVESERVERS: 127.0.0.1
  ZBX_ACTIVE_ALLOW: true

  ZBX_VMWARECACHESIZE: 128M
  service:
    type: ClusterIP
    port: 10050
    targetPort: 10050

zabbixweb:
  enabled: true
  image:
    repository: zabbix/zabbix-web-apache-pgsql
    tag: ubuntu-5.4.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  ZBX_SERVER_HOST: zabbix-server
  ZBX_SERVER_PORT: 10051
  DB_SERVER_HOST: zabbix-postgresql
  DB_SERVER_PORT: 5432
  POSTGRES_USER: zabbix
  POSTGRES_PASSWORD: "${SECRET_ZABBIX_DB_PW}"
  POSTGRES_DB: zabbix
  service:
    type: NodePort
    port: 80
    targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host:
      paths: []
  tls:
  - hosts:
    - "zabbix.${SECRET_DOMAIN}"

livenessProbe:
  path: /
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
