---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-config
  namespace: utils
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: rook-ceph-block
