apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
      - peer-address: 172.16.0.254
        peer-asn: 65000
        my-asn: 65100
    address-pools:
      - name: global
        protocol: bgp
        addresses:
        - 172.27.0.0/25
        bgp-advertisements:
        - aggregation-length: 32
          localpref: 100
          communities:
          - no-advertise
        - aggregation-length: 24

