---
# localhost
- name: Initalize remaining nodes
  hosts: localhost
  vars: 
    sshUser: root
    clusterFqdn: cl.k3s.mrry.io
    clusterIp: 172.25.0.1
    clusterCidr: 172.26.0.0/16
    clusterDns: 172.26.0.10
    serviceCidr: 172.27.0.0/16
    clusterDomain: k3s.mrry.io
  
  tasks:
  - name: join m2
    shell: k3sup join --host m2 --user {{ sshUser }} --server-user {{ sshUser }} --server-name {{ clusterIp }} --server --k3s-channel latest --k3s-extra-args="--disable servicelb --disable traefik --node-taint node-role.kubernetes.io/master=true:NoSchedule --cluster-cidr {{ clusterCidr }} --service-cidr {{ serviceCidr }} --cluster-dns {{ clusterDns }} --cluster-domain {{ clusterDomain }}"
  
  - name: join m3
    shell: k3sup join --host m3 --user {{ sshUser }} --server-user {{ sshUser }} --server-name {{ clusterFqdn }} --k3s-channel latest --server --k3s-extra-args="--disable servicelb --disable traefik --node-taint node-role.kubernetes.io/master=true:NoSchedule --cluster-cidr {{ clusterCidr }} --service-cidr {{ serviceCidr }} --cluster-dns {{ clusterDns }} --cluster-domain {{ clusterDomain }}"
  
  - name: join w1
    shell: k3sup join --host w1 --user {{ sshUser }} --server-name {{ clusterFqdn }} --k3s-channel latest 

  - name: join w2
    shell: k3sup join --host w2 --user {{ sshUser }} --server-name {{ clusterFqdn }} --k3s-channel latest 

  - name: join w3
    shell: k3sup join --host w3 --user {{ sshUser }} --server-name {{ clusterFqdn }} --k3s-channel latest 

