apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-rw
  annotations:
    {}
#    key: string
  labels:
    {}
#    key: string
  namespace: default
spec:
  selector:
    matchLabels:
#      key: string
#    matchExpressions:
#      - key: string
#        operator: string
#        values:
#          - string
  accessModes:
    - ReadWriteMany
#    - string
  resources:
    requests:
      storage: 8000Gi
#      key: string
#    limits:
#      key: string
  storageClassName: ''
  volumeName: nfs-media-rw
