---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-postgresql
  namespace: security
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
