---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-postgres
  namespace: security
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
