#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: ghcr.io/k8s-at-home/tautulli
  pullPolicy: IfNotPresent
  tag: v2.7.0

strategy:
  type: Recreate

env: 
  TZ: "America/New_York"

service:
  port:
    port: 8181

ingress:
  enabled: true
  hosts:
    - host: tautulli.mrry.io
      paths:
        - path: /
          pathType: Prefix

persistence:
  config:
    enabled: true
    mountPath: /config
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 512Mi
    skipuninstall: false

podSecurityContext:                                                                                    
  runAsUser: 568                                                                                       
  runAsGroup: 568                                                                                      
  fsGroup: 568                                                                                         

resources:
  requests:
    memory: 250Mi
    cpu: 500m
  limits:
    memory: 1500Mi
    cpu: 1000m
