---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coredns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://coredns.github.io/helm
      chart: coredns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: coredns-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: coredns
    fullnameOverride: coredns
    rbac:
      create: true
    replicaCount: 3
    isClusterService: false
    serviceType: LoadBalancer
    service:
      externalIPs:
      - "${SVC_COREDNS_ADDR}"
      externalTrafficPolicy: Local
    servers:
    - zones:
      - zone: ${SECRET_DOMAIN}
        scheme: dns://
      - zone: ${SECRET_DOMAIN_2}
        scheme: dns://
      port: 53
      plugins:
      # Enables console logging
      - name: log
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Allow automatic reloading of Corefile
      - name: reload
      # Detect forwarding loops
      - name: loop
      # Static hosts
      - name: hosts
        configBlock: |-
          172.25.0.5 alert-manager.${SECRET_DOMAIN}
          172.25.0.5 grafana.${SECRET_DOMAIN}
          172.25.0.5 jackett.${SECRET_DOMAIN}
          172.25.0.5 plex.${SECRET_DOMAIN}
          172.25.0.5 prometheus.${SECRET_DOMAIN}
          172.25.0.5 qb.${SECRET_DOMAIN}
          172.25.0.5 radarr.${SECRET_DOMAIN}
          172.25.0.5 requests.${SECRET_DOMAIN}
          172.25.0.5 rook.${SECRET_DOMAIN}
          172.25.0.5 sonarr.${SECRET_DOMAIN}
          172.25.0.5 tautulli.${SECRET_DOMAIN}
          172.25.0.5 traefik.${SECRET_DOMAIN}
          172.25.0.10 coredns.${SECRET_DOMAIN_2}
          172.25.0.15 blocky.${SECRET_DOMAIN_2}
          172.25.0.20 plex.${SECRET_DOMAIN_2}
          172.25.0.30 qb.${SECRET_DOMAIN_2}
          172.25.0.31 jackett.${SECRET_DOMAIN_2}
          fallthrough
      # Set up local resolution
      - name: etcd
        configBlock: |-
          stubzones
          path /skydns
          endpoint https://172.24.0.20:2379 https://172.24.0.21:2379 https://172.24.0.22:2379
          tls /etc/coredns/coredns-etcd/cert.pem /etc/coredns/coredns-etcd/key.pem /etc/coredns/coredns-etcd/ca.crt
      # Set up cache
      - name: cache
        parameters: 30
    extraSecrets:
    - name: coredns-etcd
      mountPath: /etc/coredns/coredns-etcd
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - coredns
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 200Mi
        cpu: 50m
      limits:
        memory: 500Mi

