k3s:
    ssh_key: ENC[AES256_GCM,data:TATPigWApEDeL4Ottm9r13ebx0LLP6UOKCD7m1E1owY9naDaR4zJh9n9M5cNZ8Tc61eLthzumpzLoA/bFFus9G2z54/ZBMHAMTasfJvLTrm3ovaJByiq13EtS9qh,iv:G2WPmpgiKW3+uE0Jy4++lDW8G/wRFXfxpT6q7/4Yejw=,tag:1qWnKBzQiAG0d3kGc/Y7PQ==,type:str]
proxmox:
    pm_password: ENC[AES256_GCM,data:CMLQp0xGjSwXtVVXeqE=,iv:Ka2GJAogvoEfrhC6mESCo0Z/jk9T/0C79SJCHgzUXbI=,tag:KNeGf8s2idwC2U35YsN5ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-24T20:09:15Z"
    mac: ENC[AES256_GCM,data:TZMW8GZLBN0yXik1HcNBwLVoU8lxxEUzaEcKeuSw/1NVxMe569S1LzT5ZuECPQQmCw8lOSXEXnZtcSYLvIzp/5gafa7Osy0s+yZ4DGJWtkuvDhj03sZVXti6rP5EKEXYFI9i1jGc8l9WZqcSJJpq5lib0SgDblkg0qgLfDkcHBI=,iv:cGwa9M5Y/f3y5yb1ZTQeKh38GCqqfsRFwG+0DHkz+eU=,tag:2uEVSnjzUeECD7oKatjiUw==,type:str]
    pgp:
        - created_at: "2021-05-24T20:09:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8mUYP7vXQBBAQwA4Dp0qTeJxDOUOVMjgCCKHvmXeftKoNkHROtUhs24u+hC
            yk9GY3TIqtvmY2QTgtOOfdusEiZdYE0U3//hQnXBWMfNTZNJGfFVBC4+FUWw6MYW
            ExG09K4HH76MKRqh1wNTTczlnse2wUc05iuqU3f5DV63wNDrBICJVqe8Fqrr/DNX
            Aqaxq0WpL6yAgbsbqqtCNZuyBFj/dvWH0rgP+PgHoQpK6aIeqeaM8MSl10QiRASN
            hMldC/BZtHnNEX9uYBKxFZDvQneCvF2qzpzjJr7iyl8txlP6mxAjw4UpCSlmszFL
            U2LlCa3/DyPRubrzN62mu9Eh/iDKCEBMaesdpMdpFx4i7tyN1/wMzBSyiz2jTcZQ
            enuA5AbZ6P5SuP80addeZ5A5BI+vRkLtgeqf7CM07k4WPoYU08waXS2CN8KASre2
            KmuZq/4f/DzjGpBLe00P76DV591cLpz2Xwlgv51/igGJMcXRMqxSxKBjrIyrjdCg
            glSMxATlSF3F9WA1L9iY0l4BiTG8k4dcHVrTmDk2YFZA6AlnXugz9kXitPmQoDBp
            MGTbePql0OQucFKyz5HKDHR5fYdcSORvfiuW1wDB8bk1IpBXtKBDKNceefaVwriX
            aL1E/nlykIarqDYtULuz
            =2Wxm
            -----END PGP MESSAGE-----
          fp: 1797E88B0B0CE9D2514A1C841F4200D33179FA67
    unencrypted_suffix: _unencrypted
    version: 3.7.1
