k8s:
    ssh_key: ENC[AES256_GCM,data:Ioz903OxdLjx/NOczpvtU0DbTt2PAxp/UKPDQ/xT9QhKeL8mDngsLCaLPUhqp/3WAzCP3OWmY8H6xwbZUChesJGibehKrpHBCEaLgUG/lQDmJal+PYgVCQowedGI,iv:akH14KjepKfigayyCUEo//T/OIG22hwlma6Nunksth4=,tag:JLhtp1uMsXRa9hReeVax5g==,type:str]
proxmox:
    pm_password: ENC[AES256_GCM,data:CMLQp0xGjSwXtVVXeqE=,iv:Ka2GJAogvoEfrhC6mESCo0Z/jk9T/0C79SJCHgzUXbI=,tag:KNeGf8s2idwC2U35YsN5ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-27T08:57:38Z"
    mac: ENC[AES256_GCM,data:ifPELz6Sg66nlQMGeFf5nLTfTH+cUGZtqKWjeNCyZIlxw2n2gviUOryEunuLip5h3L1c7cHfr5eiWC6+lBHPdHsDZrgSac2hEhtM+oWH2/ePTU/SCSUbn2AsHJCT5v2i1osJI05j5p8HTAOI29MmtprkFZsi66rUBfFEVCKXI+c=,iv:95MnGNMrvTHonIG1Cr/Isvwf/XbFluPf0TDjkmiIzUo=,tag:qT53oh21sgha/UY0o3Jwdg==,type:str]
    pgp:
        - created_at: "2021-05-24T20:09:14Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8mUYP7vXQBBAQwA4Dp0qTeJxDOUOVMjgCCKHvmXeftKoNkHROtUhs24u+hC
            yk9GY3TIqtvmY2QTgtOOfdusEiZdYE0U3//hQnXBWMfNTZNJGfFVBC4+FUWw6MYW
            ExG09K4HH76MKRqh1wNTTczlnse2wUc05iuqU3f5DV63wNDrBICJVqe8Fqrr/DNX
            Aqaxq0WpL6yAgbsbqqtCNZuyBFj/dvWH0rgP+PgHoQpK6aIeqeaM8MSl10QiRASN
            hMldC/BZtHnNEX9uYBKxFZDvQneCvF2qzpzjJr7iyl8txlP6mxAjw4UpCSlmszFL
            U2LlCa3/DyPRubrzN62mu9Eh/iDKCEBMaesdpMdpFx4i7tyN1/wMzBSyiz2jTcZQ
            enuA5AbZ6P5SuP80addeZ5A5BI+vRkLtgeqf7CM07k4WPoYU08waXS2CN8KASre2
            KmuZq/4f/DzjGpBLe00P76DV591cLpz2Xwlgv51/igGJMcXRMqxSxKBjrIyrjdCg
            glSMxATlSF3F9WA1L9iY0l4BiTG8k4dcHVrTmDk2YFZA6AlnXugz9kXitPmQoDBp
            MGTbePql0OQucFKyz5HKDHR5fYdcSORvfiuW1wDB8bk1IpBXtKBDKNceefaVwriX
            aL1E/nlykIarqDYtULuz
            =2Wxm
            -----END PGP MESSAGE-----
          fp: 1797E88B0B0CE9D2514A1C841F4200D33179FA67
    unencrypted_suffix: _unencrypted
    version: 3.7.1
