apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitnami-charts.yaml
- coredns-charts.yaml
- deliveryhero-charts.yaml
- grafana-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- rook-ceph-charts.yaml
- traefik-charts.yaml
- node-feature-discovery-charts.yaml
