apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- authentik-charts.yaml
- bitnami-charts.yaml
- bootc-charts.yaml
- cetic-charts.yaml
- coredns-charts.yaml
- deliveryhero-charts.yaml
- falco-security-charts.yaml
- grafana-charts.yaml
- hajimari-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- kasten-charts.yaml
- kubernetes-sigs-descheduler-charts.yaml
- lwolf-charts.yaml
- prometheus-community-charts.yaml
- rook-ceph-charts.yaml
- stakater-charts.yaml
- traefik-charts.yaml
- node-feature-discovery-charts.yaml
