---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reverse-proxy
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: reverse-proxy
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: 
      tag: 1.2.0
    timezone: "America/New_York"
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        external-dns/is-public: "true"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
      hosts:
      - "proxy.${SECRET_DOMAIN}"
      tls:
      - hosts:
        - "proxy.${SECRET_DOMAIN}"
        secretName: unifi-cert
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      existingClaim: unifi-config-v1
    mongodb:
      enabled: false
    logging:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.2.1
          pullPolicy: IfNotPresent
        loki:
          url: http://loki:3100/loki/api/v1/push
