---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-controllers-metrics
  namespace: calico-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
  podMetricsEndpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
