#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: ghcr.io/k8s-at-home/plex
  pullPolicy: IfNotPresent
  tag: v1.22.0.4163-d8c4875dd

strategy:
  type: Recreate

env: 
  # TZ:
  # ADVERTISE_IP: 
  PLEX_CLAIM: "claim-DupUJah9RNDmz3p2eqCx"
  # ALLOWED_NETWORKS: 172.16.0.0/12,10.0.0.0/8,192.168.0.0/16
  # # NOTE: Plex preference options are camelCase and CASE SENSITIVE!
  # # You can do horrible things to your Plex configuration if you are not careful
  # # See a full list at https://support.plex.tv/articles/201105343-advanced-hidden-server-settings/
  PLEX_PREFERENCE_0: "allowedNetworks=172.16.0.0/12,10.0.0.8/8,192.168.0.0/16"
  PLEX_PREFERENCE_1: "FriendlyName=k3s"
  PLEX_PREFERENCE_2: "EnableIPv6=0"
  PLEX_PREFERENCE_3: "logDebug=0"
  # PLEX_PREFERENCE_4: "DisableTLSv1_0=1"
  # PLEX_PREFERENCE_5: "LanNetworksBandwidth=xxx.xxx.xxx.0/18\,xxx.xxx.xxx.0/24\,xxx.xxx.xxx.0/24"
  PLEX_PREFERENCE_6: "TranscoderQuality=2"
  PLEX_PREFERENCE_7: "TreatWanIpAsLocal=1"
  PLEX_PREFERENCE_8: "TranscoderH264BackgroundPreset=veryfast"
  PLEX_PREFERENCE_9: "ScheduledLibraryUpdatesEnabled=1"
  PLEX_PREFERENCE_10: "DlnaEnabled=0"
  PLEX_PREFERENCE_11: "TranscoderCanOnlyRemuxVideo=0"
  PLEX_PREFERENCE_12: "autoEmptyTrash=1"
  PLEX_PREFERENCE_13: "TranscoderToneMapping=0"

service:
  port:
    port: 32400

ingress:
  enabled: true
  hosts:
    - host: plex.mrry.io
      paths:
        - path: /
          pathType: Prefix

# -- Enable devices to be discoverable
hostNetwork: true

persistence:
  config:
    enabled: true
    mountPath: /config
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 8Gi
    skipuninstall: false

  transcode:
    enabled: true
    emptyDir:
      enabled: true
    mountPath: /transcode
    medium: "Memory"
  
  media:
    enabled: true 
    emptyDir:
      enabled: false
    mountPath: /media
    existingClaim: nfs-media-ro
    accessMode: ReadOnlyMany
    size: 8000Gi
    skipuninstall: true

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  supplementalGroups:
  - 44
  - 107

resources:
  requests:
    gpu.intel.com/i915: 1
    cpu: 1000m
    memory: 2048Mi
  limits:
    gpu.intel.com/i915: 1
    cpu: 8000m
    memory: 16384Mi

