---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.14
    env:
      TZ: "America/New_York"
    replicas: 3
    service:
      main:
        type: LoadBalancer
        externalIPs:
        - "${SVC_BLOCKY_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 4000
      dns-tcp: 
        enabled: true
        type: LoadBalancer
        externalIPs:
        - "${SVC_BLOCKY_ADDR}"
        ports:
          dns-tcp:
            port: 53
            name: dns-tcp
            protocol: TCP
            targetPort: 53
        externalTrafficPolicy: Local
      dns-udp: 
        enabled: true
        type: LoadBalancer
        externalIPs:
        - "${SVC_BLOCKY_ADDR}"
        ports:
          dns-udp:
            port: 53
            name: dns-tcp
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    config: |
      upstream:
        externalResolvers:
        - tcp:  1.1.1.1
      conditional:
        mapping:
          ${SECRET_DOMAIN}: udp:${SVC_COREDNS_ADDR}
      blocking:
        blackLists:
          ads:
          # https://oisd.nl/
          - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
          - ads
      clientLookup:
        upstream: udp:${GATEWAY_ADDRESS}
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    prometheus:
      serviceMonitor:
        enabled: true
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - blocky
          topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
