---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v5.24.0
    env:
      TZ: "America/New_York"
      PGID: 65539
    service:
      webserver:
        enabled: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "book"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-authentik@kubernetescrd"
        hosts:
          - host: "calibre.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "calibre.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-config
      media:
        enabled: true
        existingClaim: nfs-media-nas-pvc
        mountPath: /media
    resources:
      requests:
        memory: 250Mi
        cpu: 300m
      limits:
        memory: 1000Mi
