---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.23.3.4707-ebb5fe9f3
    env:
      TZ: "America/New_York"
      ADVERTISE_IP: "http://${SVC_PLEX_ADDR}:32400,https://plex.${SECRET_DOMAIN}"
      PLEX_PREFERENCE_1: "allowMediaDeletion=0"
      PLEX_PREFERENCE_2: "enableIPv6=0"
      PLEX_PREFERENCE_3: "FriendlyName=plex.${SECRET_DOMAIN}"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
      - 44
      - 109
    service:
      main:
        type: LoadBalancer
        externalIPs:
        - "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
        ports:
          http:
            port: 32400
      dnla-tcp:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
        ports:
          dnla-udp:
            port: 32469
            protocol: TCP
            targetPort: 32469
      dnla-udp:
        enabled: true
        type: LoadBalancer
        externalIPs:
        - "${SVC_PLEX_ADDR}"
        externalTrafficPolicy: Local
        ports:
          dnla-udp:
            port: 32469
            protocol: UDP
            targetPort: 1900
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/service.serversscheme: https
        hosts:
        - host: "plex.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "plex.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      media:
        enabled: true
        existingClaim: nfs-media-nas-pvc
        mountPath: /media
        readOnly: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: feature.node.kubernetes.io/custom-intel-gpu
              operator: In
              values:
              - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 2000m
        memory: 4000Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 8000Mi
    podAnnotations:
      configmap.reloader.stakater.com/reload: "plex-promtail"
    addons:
      promtail:
        enabled: true
        image:
          repository: grafana/promtail
          tag: 2.2.1
        loki: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        logs:
        - name: promtail/plex
          path: "/config/Library/Application Support/Plex Media Server/Logs/*.log"
        - name: promtail/plex/plugins
          path: "/config/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/*.log"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        securityContext:
          runAsUser: 0
