# yamllint disable
kind: Secret
apiVersion: v1
type: secrets.kanister.io/aws
metadata:
    name: k10secret-backblaze
    namespace: kasten-io
stringData:
    aws_access_key_id: ENC[AES256_GCM,data:od21PeNchqThsBIsjiDthUgxRZgnmAh/iQ==,iv:idcLwuKQQCMlAcV2uMOV3I24sKXUtrJcvlnKAFzv9R8=,tag:j97A5pfhh3uXEOJBOX0aQA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:24jmT9M11u2R4ATgzqnTuHlgXEzjhUmoid3qdKacZA==,iv:NlZpIdiFl8UZYlBj8BiOV/jufiF/w0eA3XwpwJ3GFc8=,tag:103odaw5kZ6dvFFd+Y9jzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-25T22:37:51Z"
    mac: ENC[AES256_GCM,data:65Jwl5LxjmOGZs7oHFjiWkhAVn576kqqaHJk635igdR7tFAp8yc+mKAbOmH5wfue8JuRih+/IIEXLdF9I1tXbsOsnGkhZvBxuRtQ0mq8D0TfC2e++rY80+9Z3SSFt3j/LyGlzvI+iK0D1PbrJEQJn6J2gdNBoWZZ8tOAanslz7w=,iv:VipYZHGC3Mti/DxOVbtmrQ/OfaDBuRixdNGIPOgcjOI=,tag:tSUgwJWI6rfpMEr1TiD+Dg==,type:str]
    pgp:
        - created_at: "2021-06-25T21:05:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8mUYP7vXQBBAQv8DFEkaezc/XGM91EZ/Yyx9DgYyTvmIpLEldjJUiGPl6pz
            VRPZQ/6d7OaecW5mCW48OWR7+LdTTiKvTKpO5quUVNq2UHxUdMwFH0AIgodGv61k
            SdOTzOKYj0n1/0f9v8rOpa6hXWAdXFZLcpc6Z1NJEnFk6kNhU6vyQj645EBdqiLC
            Qg6bcsPQEtTPMN4Rj0BC2c/QBT4sQ6UpwG7eoMsP4Dr1i/2FRbB86IRXrRDV1XcV
            tUJPMWxR9jGQPBUN52ZwxBbXDCVEzeBUclRhB95J3cah5FBSPNvZp2Sh8C9JGKVH
            14erSrrfpEjYrzueebQ+4IxRCNd8s8QwOraQR3nUnkkfE9Z6NR8GreILaR7ZUGwQ
            G4u6dWsE5SiIdmFppj6SYsaY4zJUbjppiYyuUmLSV2J8W15xSzxZ30aNk+drV9kL
            LOHBC2ppO33BvF/9ZWk6KwdVzvpIv+LJzhcMLrT38D1/s70TLbUDc+uIWkAXiIXd
            gSlKA9gOtkDx0NqamyPH0l4BZ4bCHbHhOwOWm8JwYDBJMua5y2ehkVFk/id9pcsu
            55+5JmPtdoiGdT8ei6tnXHcqm+H1F3xenCkoFsw7foDLaDPc7kzMDkw9Q8B62z7K
            qdOdb2b3qcC3Gt0XP24s
            =MJxJ
            -----END PGP MESSAGE-----
          fp: 1797E88B0B0CE9D2514A1C841F4200D33179FA67
        - created_at: "2021-06-25T21:05:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA27ETZ4qli6oAQ//WzZVWD6BPh/OTl6WjBru9If9Qs3yk2UvogGkiUcGsUP8
            c5BKzaV9//+wVdUyubKLYffEvyoNbJ7D2pMs1CLfUw100vqUV+CaxjhJu5oejwc2
            GzNhu0khSBy8ASzlQpO7W0DDcTS1fQXB5Z6/PYkWta/SsTQ2DTWWQAQgmkR8+fHI
            0ZrKGuAzz4XpKcEiUejL6eYen+MAVaEkA49k/b5JNeXTquJdvlbmp1Ovod6ZFtVN
            ntmP+ugBui12CJTjyM/YmX7rQLI2hYfEpsqp8cAqx1fzPVXjAQZYUUa1ST5ZQ9O7
            RtT7qmLv/2B+9rViq10ssVcw75JeRUO+ECFVp6NM2Ofjwk5SAet+yytY0Vshv/cF
            xEJOX5vq8qKsWIpu3/3EWwHLicVKWdAbGTS5mpNc9ig6q0/SDjE0a/TeywTwgzns
            qT/IFWpHbdDIYBjZlcHDA/MlJtsIFypjkivfSpjVVVLO0jby+tQkEbFBmeZGX8Ee
            kJ9+S2n9jrI9VeHUpIaxR3g/6nplNiKIH9X3kelGLvCv8Q5j0yYE+nLNa+QOwTf7
            1tmIsCofk8jebVTwfmzBJwbmHDNNPtwKaGm87QzYP/cVv/cvgnFi+sMdpHZzxmlz
            MfQLvxW3gbIJma8Z0Efs69GsCgg1l51fry4o7ErSxGeMngfoW3s9p7oTHdX0t7/S
            XgFHowfSCDnr8nV/680JraqmPng+qpNPXsm0vpYySfcPJpjQxjK8LOr1ZZqHeQG/
            pdZGACluLcEVDtxyaT8k756HTc11qqjOuXjxKGmkrRft3uAF99oEFmr9wnkDeaA=
            =5dxO
            -----END PGP MESSAGE-----
          fp: 5375D143C4FEC43EBED1D1294823D5B58339B759
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
