# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CKpkHgpQkPbRsyY=,iv:2ApRYtG/k8ck+uzwyr5zY0QevG03+MlRpuQjgMzPfjM=,tag:mkFsMYW8W1ZqAsIbv5cfHQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YrcfoaNCskBq33QbXJZlLl6G,iv:3mWlWTs0ZRJ9UCKOr6kGGWFGSDZ+bdEryL4Y10SOps4=,tag:bwg/+ahL2Gx/KMnfvpShQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-14T01:41:57Z"
    mac: ENC[AES256_GCM,data:0/DTjWh5pFlkDtqMVYxNdO2Tcmr6ZbFzBmjfsDBZMjGLq9L45vbKrFBz0Etn6M8YRRMFMDZwPJqO4CYSYUXGlk+u183oR7Yu/axE3CE2GC1PL78Ajcg2XeDB/YSjwu47xf6rIUeq/T8vNUYV6ymtb3YqJoeqWqjzPpKJ//WlaaM=,iv:LZSN+EALJKioAAIj/R0D6Cr6YWLWVHg7iwRU7RvjD8o=,tag:4US1iYA/wKTV20iV1/dJHg==,type:str]
    pgp:
        - created_at: "2021-06-14T01:41:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8mUYP7vXQBBAQv9EfAju4pfegkAY6XY2uggY2WBsQOqGuYzZBRXHA+kteCK
            GFZ16f0GWfSlNTAbjEsvz7ipOIpIOsZuBusRDLJ4KjM7FiDO8j7lnNzgB6Q/+jao
            YftP3ro9ZeBUY/OTDWwgKLShvTNN98Xznm/JA8Y1e8bS4sgakwW548UT6x4IMxR7
            2i5wqEUDTXIGS1fZDFUseAK1p32oorU6HD1VQAkRf4QQHMJj/fxux+ucv91FYaMV
            QRlKWu8QzjeGRZVUepuyqtByozRi9MEwSq87e11VYkylL1YslapVBMxlgu85zqwa
            eMy4G50ZJlue2OB21d05jLnU8rv+Va51RV/NlOYmgz8ikeW9UriBUqa0I6t/AwfO
            3qilazqDCFCRVD+nnq6pFSkQloAzjXGiBxXC0YvB9YX8bwsMurziaeYYZ0DSKPOm
            4/Y998ETOw78kK3gOO7UQLYpyGREUT770zngudDE0sUbjk2etNUPBTqCvmH3Jnyt
            NXsLugwYvYnomWosipED0l4Ban6Q2Aavev+vyZEPK7GlminTFbiBQoFEZnm9K2vA
            JVHGKKpkbohSzMXhDBl5ONrqqgxUsQN4APrBG9KVRvLghc7TXEnLKb3DIeOweEiR
            5lqZzziVxjQsd4mT1hoP
            =V3yV
            -----END PGP MESSAGE-----
          fp: 1797E88B0B0CE9D2514A1C841F4200D33179FA67
        - created_at: "2021-06-14T01:41:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA27ETZ4qli6oAQ//ZbtAMILTpIhq3Oyuvid1xMBDR6j0pKEQUXx2R3TRJvdD
            Zfm1059RUdjaB8f84JTjU4IZFpj0qhNc8zc8z0zhKm9cWmaDeuFuJ+o/Bha0r0OP
            Hnp39/0XqCRW/7bRmCkgfz00wt4l6XC+3RtCY8SdL9Fdd29juKzQmFJz+A0Tk9KI
            PgQkoUqCkDITOE+kXLS0C/38OdPkY7GLkPrEznWjLVnxldHfeIjNmGLbAozX0WqS
            1sWYYG08zQvyHeoBL7stn3M1nvgh8Jkrl3+RHL3aHzgXQgUlJXPSEfdlZTwI+Vqb
            y15wN3Z5h5fyJ3cDHPVRD24uFMCw/51FW/QpKNo2X5HswloNzzifh1ncv/dqFuN+
            wui9geHHbxbFM9E6vvMrZJrUSSEgdq6dgZu8RuHIqddLyu7b7u0ZO3VwpYMgbomK
            AVBdYrpjc5AN/wtCYT0T/Tex3pU4hYTH353fIIc2cUXBwk2d9LpthMIYXyZ0HCAD
            HndUa7/fytRDyd659DNT9z7ssKTHyMvSaD2+QcIIFdnm/SmcCh5zzngcuphI5Xkv
            Aw+ZUbF4CSfCp34SoJdKbmeGQaQmYL02/HsVsXJpdLEDam7ZBphGdtUMCmLPvqj9
            5oQ/avvqCH929VUgUxGbs3PxeQTSoz4KCqEChVODyDRL3w3X32ese3UjvnazN6bS
            XgF9Ye0FPppEBuT61jBEce/O6u9ug2/reu/ks8QNHHzIQbVIkzlSG5iq2cOHxD4k
            MNTaH2SgCetdHcA91LPXr1k+GyeftMSUirUmXvqimQvQK/qUgmjXV1P/fhdXL6U=
            =0+QC
            -----END PGP MESSAGE-----
          fp: 5375D143C4FEC43EBED1D1294823D5B58339B759
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
