# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ADMIN_PASSWORD: ENC[AES256_GCM,data:jx/RHNzZgfO9tvH0Bi4=,iv:SqmNcjM1dC0y+yB0KPNGqpcRMmqNae9cXLHNvsaV760=,tag:hXOGeFHIO5ixUmyfeJVMvQ==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:++aQLjdflYVbisoIxPUYemlXSs7NSU5k0iId82uNbQMdLuITfULKZc0OzuwUofwFEndtZHxdfVlEEohNTcOOjQ==,iv:Y9nFqc5NGkI4sZJF99fFWXrA3kEi6IWD0VwJWIlI9gw=,tag:fK9rwKHQMEzICdFVsp0eIA==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:eTB82c8YA3E2zCmexKf17Skqih3OhQDOknxYlFVfha6yPZ4l6nPLxqw8h/wa5yPK/7wvf+dkJq98lBGFmWsMMA==,iv:grDG+gauFludaPpkdVaroGPLkCKXdeqOkMxIsjrmEV0=,tag:m7HIw1Ced/Skl/odBcJtNw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:93BDZJmTHzNrneqcHOIZcjyS,iv:8H0TQshYBsUD3w4oRrT+8jgUujujKcx0J8U3/4nfdWc=,tag:kxtJK00/4AGQcpnEvnYCtg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7x7Aj6jKbQ==,iv:v4fTxtHM307EiwvdvGZ7QsaNSN/x1tDzoVjWCwsW8xU=,tag:9MZXiJNjuELj7fjYp/5rdw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:kDxIdSiJYwVr+N2U,iv:uaZZRE9ipec8mQxhkfRTrOfnrnGnFUY2aM33aa1Ka60=,tag:1GUuAMfetchLiEs+7ZMqOw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:tLY+EaFT9ioZqUn3gJo=,iv:6v7+mwT1pkosHU6N9cAIwf+NZ5KTsALv2dA3V2Aep5I=,tag:PpeyhlDjtsa//JafjDhyiQ==,type:str]
    SECRET_PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:ISmJc9ikaIjiOinpMeFSYXZq7/WudPvDBSs=,iv:8KIF6PXUoxhiFtCcwkIaRAbqSbeLePBlaZK+GFGM0Xw=,tag:Y4TBRLQxBIeOvWpOmPf4Bw==,type:str]
    SECRET_SENDGRID_API_KEY: ENC[AES256_GCM,data:Sp6MGAKOr1vk8QhiAqqPURNrtX0EhJ7auVcYTRtdowwiJUOKjyJ//yF96Y1TWf26vqAN1r4zCoRPque9BEFEXSEh1M28,iv:AqlcU8yyS7Wi/oolLcHtwvZthhAXTzWIij2kkwdQTBc=,tag:/+X3xTXEoOC35I7pxIzB0w==,type:str]
    SECRET_SHLINK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:dXRiJ/rzrnl3g4f3J0HXN5HzclWulsfkLM78M4UV3qxMXwgx6EVePMXCSzCya/khvc/R/3F1W416H/Ro9vUsTg==,iv:B8og0styY7ZyTbOkMzDvlbFnYV0XAus3scSSUu+xo+s=,tag:n/JqjjmqJLDBgxgV0M3aJQ==,type:str]
    SECRET_SHLINK_API_KEY: ENC[AES256_GCM,data:8wtIXJR1F7MInlq9bQoxtp/4eGhtXPsU0/0vVh05NR9F2Viw,iv:htbAh1TBzoqdmIqvDJ8ILqFFpBXvLdzX2XNRB7a0V6w=,tag:LUBTbC9KzdfLBOzrDulOJw==,type:str]
    SECRET_STATPING_POSTGRES_PASSWORD: ENC[AES256_GCM,data:rKXyE3tkIbq9WFJbNSh/aYLKR5EtDgyW76WbTN17UiywRU1aEP1tqsM0hmrc1sgdhpX//j1FxlrHeNW6WFBaNg==,iv:v3+Jx2TEo1HNMdA+2Z7sk2ryaj0mtkpNHsIAtK+iucc=,tag:Md7QzMvB8QTjgpneGMoFww==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:8YGfcRPzH3Rex8y1MHMH1hqFU2M0+u7cOKvqJoQVXaRhGJRm,iv:+gn2lmfhODrjZeMX4MB40iIacJN77w8CYu9AVSPX2Ao=,tag:nMTERxpmQikPuL3FjEf4ng==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:a/AjWtiYgJ0zqd8gMuBMvbZU6d3bHXJrp8Zlut9HyP3/J8F6yicW03fRDqvyt3KX7aw414BgsWZeo4wZBoozhQ==,iv:huWK6lzpWp7NCVmUGMZC+/SKCck71lPDsFpRkCGyQRw=,tag:Xyw3rzRc0FGNEVqeVn09/A==,type:str]
    SECRET_VAULTWARDEN_DB_PASSWORD: ENC[AES256_GCM,data:dvKqB6qLjhrGsA0co3KeZx4beSHrY6C+WCTcQSMIt0Cb3fwCzLUJVQEd8xE7gAjqiKIrsJ9CJ5Q+Ddu8D2n0AA==,iv:gbFGRWQ7fXgPK1M0HYCDhC7vgfk7psLrwL+pjeRc3o0=,tag:c1eW5VNB5wpboffwmxjCag==,type:str]
    SECRET_WIKIJS_DB_PASSWORD: ENC[AES256_GCM,data:G4HYP+ew2vKqo0zHX63ZlQQg+QACZIZm9SM91d9SJJks7diK7cAQKMHbtTMJhwyYuDqkUax39KnUxFsFRRJ4GA==,iv:Em86oDT/5HkLoG+W8kdyCPzXzmhhzAAUoj9NEq1D39c=,tag:kH5ZrOuyLuL+AE9s9HchgQ==,type:str]
    SECRET_ZABBIX_DB_PASSWORD: ENC[AES256_GCM,data:hfhBlBpd5j0LvSQiQrV/KnK51N3YTyZ5eSJyDEPZ10jQzAoAbk4D0Yc2pW3+rSUWnLgSM4bMFuERGwcfA1XmMw==,iv:0DuaslJnpS+clCTP/PfttwnWjHNBXYY0IYG04cyEqEE=,tag:VuJVn8mwTyvdJGDUp8xrTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-01T01:26:03Z"
    mac: ENC[AES256_GCM,data:IRT/3CIJXnRsQbfGQe5RjjXrHPf1QK2Z+qCtfOB05xkJGO80zTgm2tyDykZDZtPvPv9nqulGcK81r3sXFJCamEzIHU1aLrMpy5/LdV2u2+3+aD1zDoGqWv5oaQn7TEQL27qjg58IvALpY04DsRpowtnwBmZExPyvN94B5d4ouCw=,iv:w8NE5sNdW98LGqaBEphpjhHbZdKjA75gBnzAebrlIt8=,tag:FcL4KNVWGuhrt5BezUfSdg==,type:str]
    pgp:
        - created_at: "2021-09-01T01:26:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8mUYP7vXQBBAQv/QdTMNgBS5KKXagS/IGFrSlMb8RTkJT93o3sx2GZPVnGt
            Q3M7atso0g12cZR8+ItPyNm/vVy71JzzP6kW/jgcBd6YpHOSrnfXss5+pFgI54HL
            DrZLg4XGDgkkqZyxcsW0fwEs/OjZNqrGBsmao4vaGfsIVGWAknJTnFpatHD7Dsu9
            KF535Fs3IJst7Z3FM5/8BHs6Gzmh4e+iVzvPAmYK7LnsWeCNl3SqMamg8Aoo5975
            /76cQZnpkHRVMWcQKha07Au15l00jaDgqgWsi5KbmWkVVyeY10iw8cGLPtWNEJmU
            kcf5tcgMlnTBZl3Uotk7XHjfwsTpdvuiebnbKpyfvFtcEhfHHErqLAdJTpjmc4ff
            dpDuzjkObLjlkhRARfK+p+Ok7XxNc8B0L6KLSKUAFDKTqibaTJr6NJlv1tgTY0mA
            C9vPhmD3jPyjtTca/i7fXWhhLU/r9wmhNZzC5Deo30L0M5rteKS6OmFrdqM5elgb
            UBQ7QCDs+fioBfiQtFZQ0lwB/jVDDKNcZiAW7t/aKwltftgscS3q1Leg059yBMeg
            FOcmaGDFXmNsNH+64vhI4jvib3x3priahKQjbJRiaKqUh39yi6jI5O49KGB4ptFk
            bswY2sDPbA5I9sBY6w==
            =eiPu
            -----END PGP MESSAGE-----
          fp: 1797E88B0B0CE9D2514A1C841F4200D33179FA67
        - created_at: "2021-09-01T01:26:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA27ETZ4qli6oARAAvPGXsqPsGPQWz0nQ5UNrlrEtGf/S7lpYQfAjZt2yAypE
            IhpdPAa73fMSbMJ+FAVyWCRZP3Wluk6CPk30QumwxvZINtULzsdyI5As2LlScpdw
            Z7hg9nN4p7N9s+DUtkl6pFEoFKfL1CFpZipBKtEF6uusI/olZVRfbdtz1Sb6xSS0
            2cOrzEG9ctmguRWtx01poA1bxSEU18w45PB++4jkpFUsVYmk172V7IIApUkfrDfi
            8xZRolegB+/NBbYsR7J2Dt4XCPVHWMkqOfrOm974dKD5Nc6bSgw+ZgpGn/5tNf5a
            d2A7RcHo0/Q3kOEbrMDRIktP9k05d0Gl0RH1mr0ig3ALg7EKjXxX6VIbyrPuuftj
            dTaKJRwFvouflg42CmZStxsulSMXeYGOLiqytwMzsrttp+MXjhaK4gIS8le72Oo7
            GuyYeyvuYHYZM2Qpsp+tmsuOrpNVNKYF/HCXLixi2idpFwKOfv44WSallYwt/SR2
            N3QpayNX0WZDkUAhb8md9Nxailjly1kK9PxYq72ZR40yimmwLYEf7kG8/zHBWJgK
            83crQERvgHo6MlyuSPkSvjajcR9pPzQKvE0yRpE6zcrdXkzXDOu8BGeVqdEWN5wD
            Fp+sDb/IUXMybv1WFUKcyLmQLrVeWHAWPAN6N2j63+fy0PYyd3rla6peG0EW06TS
            XAGoXlQWEHP7kHQj8P4jQLYFzDzXVCdBTTGYIW+6f+Ix7sZQR+4fZr5wX3Q0sN+n
            Vq7PKOkPVhv6tC0/Wdjmu55Qpds7wSqIXqmICg24qNpFL0ml8w2jgbxE3Bwi
            =wcYA
            -----END PGP MESSAGE-----
          fp: 5375D143C4FEC43EBED1D1294823D5B58339B759
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
