# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xmDI/UYBRQ==,iv:+HRkkW9/34XETLsMbelaOX97q8QTj+dw0rxf8PPJ9gI=,tag:hB6hWcg2uPRJlAlw24TV1w==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:qYNGXoK+j+Blpw21,iv:fW4B20yMlKwkEyuYqHNf2d0YiZpXL4JoMkE7ZlIFkd0=,tag:thtK2xRqrt/Vth5drj9hjA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XF4huILkZFheertumD8LrF9q,iv:I9IU6ezjTLaaQam7n1669eQ7vho5lRc5bT4nTGzkn1c=,tag:hp4wp4U5plmGLRHfjG4DhQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:zifx1uGeycAMHHyuhQg=,iv:Z6BbkcpHYBfiWKEpm0Go/aeUq4N/GgoIr0dabmBlUgY=,tag:+P11Ps7Z5B4rreYUDcH1tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-25T15:19:36Z"
    mac: ENC[AES256_GCM,data:BYYUfmKkhUZpGEp9R/KacJUuLZu0rsuCZgw7inTzHh6278s68kHjUwGPeMW1wfZHh8H0q2AuypWi2isvR3fd0JSbd/MNjjokVLmaoJxMk2oII/J4nEnoY04pa8FK6FKjjAk3AAyIFxQCq3Hll95KTE4F95wL06p3x/GCV0FUODo=,iv:b9wui/frsxb81mUzvLwg6vlH8RCXQM52tw6iJIsNfk4=,tag:8KBsJVq4Fe8WQGhpcgMJwA==,type:str]
    pgp:
        - created_at: "2021-06-15T20:58:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8mUYP7vXQBBAQv/dM5eEMx3PouzqoFoVgkIchUFHOl0xQuExV0wQe1+itGM
            iUxtYs84gfj5oIA3ws0oiS9Y97zXOgm4aHBQxjuvq91tdft32kcRyOL/t5CYjhsA
            dMu9CRI7T95WEUVd8YUwzidhzFaA7OnDxGaMW+vBHsK+pWevAzu10o/cpIZI1xgH
            HzoYzmMEZVHlM8nvA1t3inatfA+n8pF0gfi9b7/WTDjt9ZJrHsRlmNC97xTnUVh4
            nsco1qbZnggde0GOy2oXzocxnchwQVr28Dh2qguMFg1dhLP/u1W+PIHCR/IkFkVB
            V1MbwPpAzu80TjbS3bkXxzxig7baJwnXWMDF7AO/bIDyYgnQw/JYRk4yrz+r70Kz
            e2CFUNRL0t9LCtOlWlEB35eTgzQUFTIgGyEMRFTDhOrBT1mftttz0WDm8yXxSK45
            2+3r+7wuK7ysNL4F+thKqoh0/ZD0jcjo9OCvhaYOgRQpnf9H5mFnckjDjWfyuqH2
            lCiZ9+UB6q75tMI8Yi7h0l4Bi5Td+NmAWezQlC5z8qaOxMabqh3EMi6dBlIMqcBK
            2qJXwG3dhrGPj16BZRCa+3DvYMjRA+H3BBiaO4jCtDBYi4ElmqsL8q7o+SB4cAQI
            rXJ//H9Kr9fz7qe4y1Od
            =5fpG
            -----END PGP MESSAGE-----
          fp: 1797E88B0B0CE9D2514A1C841F4200D33179FA67
        - created_at: "2021-06-15T20:58:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA27ETZ4qli6oAQ/9Go359Qa3l7IOWDDdjc1h54mjTemLcSNs9NZByZOG+bue
            tjRYc5WMPHxzqSCXXdvioHwuoZ6YCXzH6R7tlcWm4Wd1Nqrj+17JrcHbWu9yABdL
            z9nm+aqhrpKtMZLuk0dbgW5XgON9kTrKp2GrOjpw6T5ybYigJfoinf+YqFnFG96l
            aEii60H6xcf/uWFUNtFmX9ie/7tAzC0PmEFgA+4ManrdzXmAo5qMzWGqOvtlz0fq
            5dRvKbR/bIWSQ5dZAS770TFZOr1M14YDdMf1O5v9rmUAPYg2OFuVCBwm7HX++BMu
            UFRrxfAsz5SyImHUqC4s0mfLX1eNYe9S7tHWRm4vxRSEHTauAXpNG7qqyiUzcbcf
            tyhLNHVSmclNWqMVrdGVatopHzL+2rZKclr97WuA9Fz+pZO+GBtGX68MeKz/+6GS
            sixpFM3vi5aBk6D9T2zgSWiZaKmsXmu2WGDJUhW7TY/0qqLOyI53gDo0O6AtF6vg
            s59Uh/QHlo0OUFUPHU2RrL/CQMsj101NkZciiT8hpn6+OD16eWnEMF3z9vQgEkdJ
            S+N4YHjYCiG89uXyibrNS+VCm2kUGz2djeS/kRT295M//Rjh8AxwR2Vi11/ZfR2e
            iOdL2KJVIw3zd7ekeA+z0yMmMzIE+n0CAPo1UrvOIj/nRgQj4/m2B/wBFv5uqM3S
            XgEu9Q2oQZBUqcSI4mSLp2CYCc+mUUyJgpKvTM4xtRf5wjI6m9pFLFjz70vvC5a0
            Pv4mZpZYuegTYKQgW1sDXfSmHEEzqMAL8ko9jS2dgq8NFu92yNNDQa4EVCIcawA=
            =7f9J
            -----END PGP MESSAGE-----
          fp: 5375D143C4FEC43EBED1D1294823D5B58339B759
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
