# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: mrry.io
    SECRET_DOMAIN_2: k3s.mrry.io
    SECRET_EMAIL: dave@mrry.io
    SECRET_CLOUDFLARE_EMAIL: cloudflare@mrry.io

