---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowswer
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: filebrowser
      version: 10.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/filebrowser/filebrowser
      tag: v2.18.0
    env:
      TZ: "America/New_York"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "folder"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-authentik@kubernetescrd"
        hosts:
          - host: "media.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "media.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser-config
      media:
        enabled: true
        existingClaim: nfs-media-nas-pvc
        mountPath: /media
    podSecurityContext:
      supplementalGroups:
        - 100
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 500Mi
