apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: arp-config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.24.0.1-172.24.0.50
