---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 14.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1265
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-authentik@kubernetescrd"
        hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${SECRET_DOMAIN}"
      api:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
          - path: /api
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        existingClaim: nfs-media-nas-pvc
        mountPath: /media
    podSecurityContext:
      supplementalGroups:
      - 100
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    exporter:
      enabled: true
      image:
        repository: ghcr.io/onedr0p/exportarr
        tag: v0.6.1
      env:
        port: 32123
        additionalMetrics: true
        unknownQueueItems: false
      podMonitor:
        interval: 3m
        scrapeTimeout: 1m
