--- 

- include: packages.yml
  tags:
  - packages

- include: kubeconfig.yml
  tags:
  - kubeconfig

- include: kube-vip.yml
  tags:
  - kube-vip

- include: calico.yml
  when:
  - k3s_control_node is defined
  - k3s_control_node
  - calico.enabled is defined
  - calico.enabled
  tags:
  - calico

- include: registry.yml
  when: mirror_registry is defined
        or (private_registries is defined
          and private_registries|length > 0)
  tags:
  - registry

- include: secrets.yml
  when:
  - k3s_control_node is defined
  - k3s_control_node
  - k3s_etcd_datastore is defined
  - k3s_etcd_datastore
  tags:
  - secrets

  
