--- 

- include: hostfile.yml 
  tags:
  - hostfile

- include: packages.yml
  tags:
  - packages

- include: etcd-secret.yml
  when:
  - k3s_control_node is defined
  - k3s_control_node
  - k3s_etcd_datastore is defined
  - k3s_etcd_datastore
  tags:
  - etcd-secret

