---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osmosis-config
  namespace: ibc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: rook-ceph-block
