---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osmosis-data
  namespace: ibc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000Mi
  storageClassName: rook-ceph-block
