---

- name: Stop all k3s VMs
  hosts:
    - pve03
    - pve04
    - pve05
  user: root
  ignore_errors: yes
  tasks:
  - name: stop all vms
    ansible.builtin.shell: 
      cmd: pvesh create /nodes/localhost/stopall

- name: Destroy all nodes on k3s-h2
  hosts: pve04
  user: root
  ignore_errors: yes
  tasks:
  - name: destroy k3s-m1
    ansible.builtin.shell: 
      cmd: qm destroy 100
  - name: destroy k3s-w1
    ansible.builtin.shell: 
      cmd: qm destroy 110

- name: Destroy all nodes on k3s-h2
  hosts: pve04
  user: root
  ignore_errors: yes
  tasks:
  - name: destroy k3s-m2
    ansible.builtin.shell: 
      cmd: qm destroy 200
  - name: destroy k3s-w2
    ansible.builtin.shell: 
      cmd: qm destroy 210
  
- name: Destroy all nodes on k3s-h3
  hosts: pve05
  user: root
  ignore_errors: yes
  tasks:
  - name: destroy k3s-m3
    ansible.builtin.shell: 
      cmd: qm destroy 300
  - name: destroy k3s-w3
    ansible.builtin.shell: 
      cmd: qm destroy 310
  
