k3s:
    ssh_key: ENC[AES256_GCM,data:N/e0ud4uD6J22qvDNHyirZJFYTUgkS6NukXpuO6YDqP3oE4MBp8hfg+XJ4ue4G4/gvBdtYWO7LYbrkRH5NQC6fzafPpBngnaJZh74NnfP2zttORRadS3PzqmcU1P,iv:RRcieT0vX3MIqzON66zrv1hi0f55myCbiCFe/9a+iP0=,tag:QpLoJTLWXDUeSQGrgqVHgg==,type:str]
proxmox:
    pm_password: ENC[AES256_GCM,data:p5asPhwINVIswG6FWJU=,iv:FyqunokAyJrWCkr0v0PfdtybLm/UxzJOm6a9SZJUQfw=,tag:zkOXYQ0RWO/XpyflHJFECA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-21T23:44:32Z"
    mac: ENC[AES256_GCM,data:remIpLgCAIpyGAizN54n6GgC4jIKwKIoYMsKVJtI1FDtpi8pRxsFIYHvnLFYpjWhjzS48z7suiO6Sv2dFZfVYCSLzCQCcVFC+9AnTN8vPuc4yojBqsUGtsVq4dCk7IcGzmU8w/sCT/qSKGtUDWy7AICpAQPnCpwVlOyvH8qkC4w=,iv:i3PQ8U8BiUhC2ay7NGOPchiTkYAD2gC08jR+dzOL2AM=,tag:/lCsPYUK5yOfiHbBMDYAyg==,type:str]
    pgp:
        - created_at: "2021-05-21T23:44:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAwOjFIk3u7ViAQv8DduvRK70BrDE7byqfV+0dKm1H53m2lAGLJ8pKWOZgurc
            83HbNa0DqNcCguJQSdv3jzmM6fVf+AyE8pW0YrQ8kjq9XiglX/5IjpFzwkt9dCon
            iZH2nKWTkQIsjFNqr0axNwu2QDlgJhgMYuWOkqzvbWwmpM3ekXB6CackZsnr71pI
            xhrQ/lP4DPbRiMuXY5GPkWtbFaouXjua9s3VGtyHS3ADDw7Xd/6XejsGJfxkzpiN
            zxEgly8XIBAVvvXsfgntZfRldofdhIrNvBhw5cGXChz/rknMxzCZKDPjyNjJA1mO
            8f4u+G7Xzx57MPLHwcwN1FBj4qPaI8dS5Hpb2MrrjNakCyGDDDvTz+JzMq8GVgcq
            2dCOl8ke460iAWJ0jAItBw3+mp8jFq7FcGERqVPFekuQSYSzGO3vCzfkyTPvo99V
            tFGoXVyCZUDAMGG8/DkmdIL2TVcHM3UQ4CmSQTqj5lrMkxncybj7FyuKWqE40Wza
            v425wX5Aje3oOanjDLQX0l4BypgPRoiunLgoaLJeMNj52sowoGdJbOV/YCf3qbp4
            XoQQTGK2+297Urs+yiNQFoTl9IPoCU12c09Il6D16IVHF6TDktlBQXrvXD/BFrep
            Lv09mcBhMBn8OFx7nPIR
            =Xyek
            -----END PGP MESSAGE-----
          fp: 4E10BCA45A6914024D0945C3DF6B15117BF7D336
    encrypted_regex: password|ssh
    version: 3.7.1
