---

# Encapsulation type
calico_encapsulation: "None"
# BGP Peer IP
# (usually your router IP address)
calico_bgp_peer_ip: 172.18.0.254
# BGP Autonomous System Number
# (must be the same across all BGP peers)
calico_bgp_as_number: 65100
# BGP Network you want services to consume
# (this network should not exist or be defined anywhere in your network)
calico_bgp_external_ips: 172.25.0.0/24
