---

# Encapsulation type
calico:
  enabled: true
  operator_manifest: "https://docs.projectcalico.org/manifests/tigera-operator.yaml"
  bgp:
    enabled: true
    peer: 172.24.0.254
    as: 65100
    # externalIPs is the network you want services to consume
    # (this network should not exist or be defined anywhere in your network)
    externalIPs: 172.25.0.0/24
  node:
    cidrs:
    - 172.24.0.0/24
  vip:
    fqdn:
    - cl.k3s.mrry.io
    ip:
    - 172.25.0.1
  cluster:
    cidr:
    - 172.26.0.0/16
  service:
    cidr:
    - 172.27.0.0/16
    
    

registration_fqdn: cl.k3s.mrry.io      
registration_ip: 17.25.0.1
cluster_cidr: 172.26.0.0/16
service_cidr: 172.27.0.0/16



