kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: security
  namespace: kasten-io
spec:
  frequency: "@daily"
  retention:
    daily: 7
    weekly: 2
    monthly: 2
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - security
  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - resource: persistentvolumeclaims
      profile:
        name: minio
        namespace: kasten-io
  - action: export
    exportParameters:
      frequency: "@daily"
      profile:
        name: minio
        namespace: kasten-io
      exportData:
        enabled: true
    retention: {}
