---
# hosts
- name: Destroy all nodes on k3s-h1
  hosts: k3s-h1
  user: root
  ignore_errors: yes
  tasks:
  - name: stop all vms
    shell: pvesh create /nodes/localhost/stopall
  - name: destroy k3s-m1
    shell: qm destroy 100
  - name: destroy k3s-w1
    shell: qm destroy 110
  - name: destroy k3s-s1
    shell: qm destroy 120

- name: Destroy all nodes on k3s-h2
  hosts: k3s-h2
  user: root
  ignore_errors: yes
  tasks:
  tasks:
  - name: stop all vms
    shell: pvesh create /nodes/localhost/stopall
  - name: destroy k3s-m2
    shell: qm destroy 200
  - name: destroy k3s-w2
    shell: qm destroy 210
  - name: destroy k3s-s2
    shell: qm destroy 220
  
- name: Destroy all nodes on k3s-h3
  hosts: k3s-h3
  user: root
  ignore_errors: yes
  tasks:
  tasks:
  - name: stop all vms
    shell: pvesh create /nodes/localhost/stopall
  - name: destroy k3s-m3
    shell: qm destroy 300
  - name: destroy k3s-w3
    shell: qm destroy 310
  - name: destroy k3s-s3
    shell: qm destroy 320
  
