---
# localhost
- name: Initalize remaining nodes
  hosts: localhost
  vars: 
    sshUser: root
    vip: 172.22.0.200
    clusterCidr: 172.23.0.0/16
    clusterDns: 172.23.0.10
    serviceCidr: 172.24.0.0/16
    clusterDomain: k3s.mrry.io
  
  tasks:
  - name: join k3s-m2
    shell: k3sup join --host k3s-m2 --user {{ sshUser }} --server-user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest --server --k3s-extra-args="--disable servicelb --disable traefik --node-taint node-role.kubernetes.io/master=true:NoSchedule --cluster-cidr {{ clusterCidr }} --service-cidr {{ serviceCidr }} --cluster-dns {{ clusterDns }} --cluster-domain {{ clusterDomain }}"
  
  - name: join k3s-m3
    shell: k3sup join --host k3s-m3 --user {{ sshUser }} --server-user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest --server --k3s-extra-args="--disable servicelb --disable traefik --node-taint node-role.kubernetes.io/master=true:NoSchedule --cluster-cidr {{ clusterCidr }} --service-cidr {{ serviceCidr }} --cluster-dns {{ clusterDns }} --cluster-domain {{ clusterDomain }}"
  
  - name: join k3s-w1
    shell: k3sup join --host k3s-w1 --user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest 

  - name: join k3s-w2
    shell: k3sup join --host k3s-w2 --user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest 

  - name: join k3s-w3
    shell: k3sup join --host k3s-w3 --user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest 

  - name: join k3s-s1
    shell: k3sup join --host k3s-s1 --user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest 

  - name: join k3s-s2
    shell: k3sup join --host k3s-s2 --user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest 

  - name: join k3s-s3
    shell: k3sup join --host k3s-s3 --user {{ sshUser }} --server-ip {{ vip }} --k3s-channel latest 

