---
# k3s-m1
- name: Install kube-vip in BGP mode
  hosts: k3s-m1
  remote_user: root
  tasks:
  - name: Pull RBAC to manifests
    shell: curl -s https://kube-vip.io/manifests/rbac.yaml > /var/lib/rancher/k3s/server/manifests/kube-vip-rbac.yaml

  - name: Pull kube-vip manifest
    shell: https://raw.githubusercontent.com/dvmrry/k3s-gitops/main/cluster/kube-vip/kube-vip-bgp.yaml > /var/lib/rancher/k3s/server/manifests/kube-vip-bgp.yaml
