---
# All nodes
- name: Update all nodes
  hosts: kube
  remote_user: root
  tasks:

  - name: update system
    apt: 
      update_cache: yes
      upgrade: dist

  - name: install curl
    apt:
      name: curl 
      state: present

  - name: install git
    apt:
      name: git
      state: present

  - name: install sudo
    apt:
      name: sudo
      state: present
  
  - name: install nfs
    apt:
      name: nfs-common
      state: present

  - name: Add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

    


# Storage nodes
- name: Update storage nodes
  hosts: storage
  remote_user: root
  tasks: 
  - name: install open-iscsi
    apt:
      name: open-iscsi
      state: present
