---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- _pvc
- bazarr
- calibre
- filebrowser
- overseerr
- plex
- prowlarr
- qbittorrent
- radarr
- readarr
- readarr-audio
- sonarr
- tautulli
