---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: librespeed
  namespace: utils
spec:
  interval: 5m
  chart:
    spec: 
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: librespeed
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/librespeed
      tag: version-5.2.4
    env:
      TZ: "America/New_York"
      PUID: "1001"
      PGID: "1001"
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "speedtest.${SECRET_DOMAIN}"
          paths: 
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "speedtest.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: librespeed-config
