---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librespeed-confi
  namespace: utils
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
