---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sharry
  namespace: utils
spec:
  interval: 5m
  chart:
    spec: 
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sharry
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: eikek0/sharry
      tag: 1.8.0
    service:
      main:
        ports:
          http:
            port: 9090
    args:
    - "/opt/sharry.conf"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "share.${SECRET_DOMAIN}"
          paths: 
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "share.${SECRET_DOMAIN}"
    config: |
      sharry.restserver {
        base-url = "https://share.${SECRET_DOMAIN}"
        bind {
          address = "0.0.0.0"
          port = "9090"
        }
        backend {
          auth {
            fixed {
              enabled = true
              user = "dvmrry"
              password = "${SECRET_ADMIN_PASSWORD}"
              order = 10
            }
            oauth = [
              {
                enabled = true
                id = "microsoft"
                name = "Microsoft"
                icon = "fab fa-microsoft"
                authorize-url = "https://login.microsoftonline.com/common/oauth2/authorize"
                token-url = "https://login.microsoftonline.com/common/oauth2/token"
                user-url = "https://graph.windows.net/myorganization/me?api-version=1.6"
                user-id-key = "login"
                client-id = "$SECRET_AZURE_OAUTH_ID"
                client-secret = "$SECRET_AZURE_OAUTH_SECRET"
              }
            ] 
          }
          signup {
            mode = "closed"
          }
        }
      }
