---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onedrive
  namespace: utils
spec:
  interval: 5m
  chart:
    spec: 
      # renovate: registryUrl=https://hajimari.io
      chart: onedrive
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/New_York"
      ONEDRIVE_DOWNLOADONLY: 1
      ONEDRIVE_AUTHRESPONSE: "${SECRET_ONEDRIVE_AUTHRESPONSE}"
    persistence:
      config:
        enabled: true
        existingClaim: onedrive-config
    resources:
      requests:
        cpu: 100m
        memory: 128M
