#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: linuxserver/ombi
  pullPolicy: IfNotPresent
  tag: version-v4.0.681

strategy:
  type: Recreate

env: 
  # TZ: "America/New_York"
  # PUID: 1001
  # PGID: 1001

service:
  port:
    port: 3579

ingress:
  enabled: true
  hosts:
    - host: ombi.mrry.io
      paths:
      - path: /
        pathType: Prefix

persistence:
  config:
    enabled: true
    mountPath: /config  
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 512Mi
    skipuninstall: false

podSecurityContext:                                                                                    
  runAsUser: 568                                                                                       
  runAsGroup: 568                                                                                      
  fsGroup: 568
