---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: statping
  namespace: utils
spec:
  interval: 5m
  chart:
    spec: 
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: statping
      version: 0.90.74
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: statping/statping
      tag: 4.0.0
    env:
      TZ: "America/New York"
      NAME: "Statping"
      DESCRIPTION: "statping deployment on k8s"
      VIRTUAL_HOST: "status.${SECRET_DOMAIN}"
      DB_CONN: postgres
      DB_HOST: '{{ include "common.names.fullname" .}}-postgresql'
      POSTGRES_SSLMODE: "disable"
      DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
      DB_PASS: "{{ .Values.postgresql.postgresqlPassword }}"
      DB_DATABASE: "{{ .Values.postgresql.postgresqlDatabase }}"
      USE_CDN: false
      DISABLE_LOGS: false
      ADMIN_USER: dvmrry
      ADMIN_PASSWORD: "${SECRET_ADMIN_PASSWORD}"
      ADMIN_EMAIL: "${SECRET_EMAIL}"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
        - host: "status.${SECRET_DOMAIN}"
          paths: 
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "status.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        mountPath: /app
        storageClass: rook-ceph-block
        accessMode: ReadWriteOnce
        size: 1Gi
    postgresql:
      enabled: true
      postgresqlUsername: "statping"
      postgresqlPassword: "${SECRET_STATPING_POSTGRES_PASSWORD}"
      postgresqlDatabase: "statping"
      persistence:
        enabled: true
        storageClass: rook-ceph-block
        accessModes:
        - ReadWriteOnce
        size: 8Gi
