#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: ghcr.io/k8s-at-home/qbittorrent
  pullPolicy: IfNotPresent
  tag: v4.3.4.1

strategy:
  type: Recreate

env:
  TZ: "America/New_York"

service:
  port:
    port: 8080
  additionalServices:
  - enabled: true
    nameSuffix: bittorrent
    type: ClusterIP
    port:
      port: 6881
      name: bittorrent
      protocol: TCP
      targetPort: 6881

ingress:
  enabled: true
  hosts:
    - host: qbt.mrry.io
      paths:
        - path: /
          pathType: Prefix

persistence:
  config:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 512Mi
    skipuninstall: false

  media:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    skipuninstall: true
    existingClaim: "nfs-media-rw"

  downloads:
    enabled: false
    mountPath: /downloads

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568

additionalVolumes:
  - name: qbittorrent-scripts
    emptyDir: {}
    ## When you want to enable automatic port configuration at startup, adjust this to:
    # configMap:
    #   name: <RELEASENAME>-scripts
    #   defaultMode: 511

additionalVolumeMounts:
  - mountPath: /config/custom-cont-init.d
    name: qbittorrent-scripts
