---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calico-system.yaml
- cert-manager.yaml
- flux-system.yaml
- kube-system.yaml
- rook-ceph.yaml
- monitoring.yaml
- media.yaml
- networking.yaml
